// Basic Imports
import { NextPage } from "next";

import {
    Box,
    Container,
    Heading,
    ListItem,
    OrderedList,
    Text
  } from "@chakra-ui/react";

// Components Imports
import Header from "@/website/Header";
import Footer from "@/website/Footer/Footer";
import BaseSeo from "@/modules/components/BaseSeo";
import BaseBox from "@/modules/components/BaseBox";

const Terms: NextPage = (props: any) => {
  return (
    <div>
      <BaseSeo title="Terms of Service" />
      <main>
        <Header />
        <BaseBox>
            <Container  maxW="container.md" m="auto" mt="4" centerContent>
                <Heading as="h1" mb="8">Terms of Service</Heading>
                <Box mb="2">
                    Welcome to Webbox AI, the AI-powered no-code website generator! These terms of service outline the rules and regulations for the use of our website and services.<br/>
                    By accessing this website and using our services, we assume you accept these terms of service in full. Do not continue to use Webbox AI&apos;s website or services if you do not accept all of the terms and conditions stated on this page.<br/>
                    The following terminology applies to these Terms of Service, Privacy Statement and Disclaimer Notice and any or all Agreements:<br/>
                    - &quot;Client&quot;, &quot;You&quot; and &quot;Your&quot; refers to you, the person accessing this website and accepting Webbox AI&apos;s terms and conditions. <br/>
                    - &quot;The Company&quot;, &quot;Ourselves&quot;, &quot;We&quot;, &quot;Our&quot; and &quot;Us&quot;, refers to our Company, Webbox AI. <br/>
                    - &quot;Party&quot;, &quot;Parties&quot;, or &quot;Us&quot;, refers to both the Client and ourselves, or either the Client or ourselves. <br/>
                </Box>
                <OrderedList>
                    <ListItem mb="4"><Text fontWeight="bold">Cookies</Text>
                    <Box mt="2">
                        We employ the use of cookies. By using Webbox AI&apos;s website you consent to the use of cookies in accordance with Webbox AI&apos;s privacy policy.
                    </Box>
                    </ListItem>
                    <ListItem mb="4"><Text fontWeight="bold">License</Text>
                    <Box mt="2">
                        Unless otherwise stated, Webbox AI and/or its licensors own the intellectual property rights for all material on Webbox AI. All intellectual property rights are reserved. You may view and/or print pages from https://www.webboxai.com for your own personal use subject to restrictions set in these terms and conditions.
                        You agree to use Webbox AI solely for lawful purposes and in a manner consistent with all applicable laws and regulations. You are responsible for ensuring the accuracy, legality, and reliability of all content and information uploaded to or generated by Webbox AI on your behalf.
                    </Box>
                    </ListItem>
                    <ListItem mb="4"><Text fontWeight="bold">Service Availability</Text>
                    <Box mt="2">
                        While we strive to ensure Webbox AI is available at all times, we do not guarantee uninterrupted access due to factors beyond our control, including but not limited to internet connectivity, maintenance, or technical issues.
                    </Box>
                    </ListItem>
                    <ListItem mb="4"><Text fontWeight="bold">Limitation of Liability</Text>
                    <Box mt="2">
                        To the maximum extent permitted by law, Webbox AI shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:<br/>
                        - The use or inability to use the Webbox AI service.<br/>
                        - Any unauthorized access to or alteration of your transmissions or data. <br/>
                        - Statements or conduct of any third party on the Webbox AI platform. <br/>
                        - Any other matter relating to the Webbox AI service. <br/>
                    </Box>
                    </ListItem>
                    <ListItem mb="4"><Text fontWeight="bold">Your use or inability to use Webbox AI</Text>
                    <Box mt="2">
                        Any unauthorized access to or use of our servers and/or any personal information stored therein;
                        Any bugs, viruses, trojan horses, or the like that may be transmitted to or through Webbox AI by any third party;
                        Any errors or omissions in any content or for any loss or damage of any kind incurred as a result of the use of any content posted, emailed, transmitted, or otherwise made available via Webbox AI.                   
                    </Box>
                    </ListItem>
                    <ListItem mb="4"><Text fontWeight="bold">Changes to Terms</Text>
                    <Box mt="2">
                        Webbox AI reserves the right to revise these terms and conditions at any time without prior notice. By using this website and services, you agree to be bound by the current version of these terms and conditions.
                    </Box>
                    </ListItem>
                    <ListItem mb="4"><Text fontWeight="bold">Governing Law</Text>
                    <Box mt="2">
                        These terms of service are governed by and construed in accordance with the laws of Australia, and you irrevocably submit to the exclusive jurisdiction of the courts in that jurisdiction.
                    </Box>
                    </ListItem>  
                    <ListItem mb="4"><Text fontWeight="bold">Contact Us</Text>
                    <Box mt="2">
                        If you have any questions or concerns about these terms and conditions, please contact us at info@webboxai.com.                    
                    </Box>
                    </ListItem>                    
                </OrderedList>           
            </Container>
        </BaseBox>
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
};

export default Terms;
